import io
from fpdf import FPDF


def generate_lead_pdf_brief(lead_data: dict) -> bytes:
    """Generates a clean 1-page PDF Brief for a given lead record."""
    pdf = FPDF()
    pdf.add_page()

    # Title Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, f"Executive Brief: {lead_data.get('company', 'Target Company')}", ln=True, align="C")
    
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 6, "Generated by SalesGenie AI Platform", ln=True, align="C")
    pdf.ln(8)

    # Lead Information Card
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "1. Prospect Details", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", size=10)
    pdf.cell(95, 7, f"Contact Name: {lead_data.get('name', 'N/A')}", ln=False)
    pdf.cell(0, 7, f"Email: {lead_data.get('email', 'N/A')}", ln=True)

    pdf.cell(95, 7, f"Phone: {lead_data.get('phone', 'N/A')}", ln=False)
    pdf.cell(0, 7, f"Industry: {lead_data.get('industry', 'N/A')}", ln=True)

    pdf.cell(95, 7, f"Company Size: {lead_data.get('company_size', 'N/A')}", ln=False)
    pdf.cell(0, 7, f"Est. Revenue: {lead_data.get('revenue', 'N/A')}", ln=True)
    pdf.ln(6)

    # Lead Status & Priority Card
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "2. Lead Status & Score", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", size=10)
    pdf.cell(95, 7, f"Priority Level: {lead_data.get('priority', 'Medium')}", ln=False)
    pdf.cell(0, 7, f"Pipeline Status: {lead_data.get('status', 'New')}", ln=True)

    pdf.cell(95, 7, f"Lead Score: {lead_data.get('lead_score', 0)} / 100", ln=False)
    created_date = str(lead_data.get('created_at', 'N/A'))[:10]
    pdf.cell(0, 7, f"Created Date: {created_date}", ln=True)
    pdf.ln(8)

    # Strategic Guidance
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "3. Strategic Action Plan", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", size=10)
    score = lead_data.get('lead_score', 0)
    if score >= 80:
        action_text = "High-priority account. Schedule a direct discovery call within 24 hours. Focus on ROI and immediate pain points."
    elif score >= 60:
        action_text = "Warm prospect. Follow up within 48 hours with relevant case studies and product benchmarks."
    else:
        action_text = "Standard lead. Add to automated email drip sequences and monthly product update newsletters."

    pdf.multi_cell(0, 6, action_text)

    output = io.BytesIO()
    pdf.output(output)
    return output.getvalue()